name: Local DevSecOps Pipeline

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]
  workflow_dispatch:  # Allow manual triggering

jobs:
  # Job 1: Environment Setup and Validation
  setup:
    name: Environment Setup
    runs-on: self-hosted  # This makes it run on your local runner
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Validate Environment
      run: |
        echo "=== Environment Information ==="
        echo "Hostname: $(hostname)"
        echo "User: $(whoami)"
        echo "Working Directory: $(pwd)"
        echo "Python Version: $(python3 --version)"
        echo "Docker Version: $(docker --version)"
        echo "Docker Scout Version: $(docker scout version)"
        echo "Available Disk Space:"
        df -h
        echo "Available Memory:"
        free -h

  # Job 2: SAST Scanning with Bandit
  sast-scan:
    name: SAST Security Scan
    runs-on: self-hosted
    needs: setup
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Set up Python Environment
      run: |
        python3 -m venv venv
        source venv/bin/activate
        python -m pip install --upgrade pip
        pip install bandit[toml] safety
        
    - name: Install Application Dependencies
      run: |
        source venv/bin/activate
        if [ -f requirements.txt ]; then 
          pip install -r requirements.txt
        fi
        
    - name: Create Bandit Configuration
      run: |
        cat > bandit.yaml << EOF
        # Bandit configuration for PyGoat
        tests: ['B101', 'B102', 'B103', 'B104', 'B105', 'B106', 'B107', 'B108', 'B110', 'B112', 'B201', 'B301', 'B302', 'B303', 'B304', 'B305', 'B306', 'B307', 'B308', 'B309', 'B310', 'B311', 'B312', 'B313', 'B314', 'B315', 'B316', 'B317', 'B318', 'B319', 'B320', 'B321', 'B322', 'B323', 'B324', 'B325', 'B401', 'B402', 'B403', 'B404', 'B405', 'B406', 'B407', 'B408', 'B409', 'B410', 'B411', 'B412', 'B413', 'B501', 'B502', 'B503', 'B504', 'B505', 'B506', 'B507', 'B601', 'B602', 'B603', 'B604', 'B605', 'B606', 'B607', 'B608', 'B609', 'B610', 'B611', 'B701', 'B702', 'B703']
        
        # Severity and confidence levels
        severity: ['medium', 'high']
        confidence: ['medium', 'high']
        
        # Exclude directories
        exclude_dirs: ['tests', 'venv', '.git', 'node_modules']
        
        # Skip specific tests if needed
        skips: ['B101']  # Skip assert_used test
        EOF
        
    - name: Run Bandit SAST Scan (Full)
      run: |
        source venv/bin/activate
        echo "=== RUNNING FULL BANDIT SCAN ==="
        bandit -r . -f json -o bandit-full-report.json || true
        bandit -r . -f txt -o bandit-full-report.txt || true
        
    - name: Run Bandit SAST Scan (Filtered)
      run: |
        source venv/bin/activate
        echo "=== RUNNING FILTERED BANDIT SCAN ==="
        bandit -r . -c bandit.yaml -f json -o bandit-filtered-report.json || true
        bandit -r . -c bandit.yaml -f txt -o bandit-filtered-report.txt || true
        
    - name: Display Bandit Results
      run: |
        echo "=== BANDIT SCAN RESULTS SUMMARY ==="
        echo "--- Full Scan Results ---"
        if [ -f bandit-full-report.txt ]; then
          cat bandit-full-report.txt
        else
          echo "No full scan results found"
        fi
        echo ""
        echo "--- Filtered Scan Results ---"
        if [ -f bandit-filtered-report.txt ]; then
          cat bandit-filtered-report.txt
        else
          echo "No filtered scan results found"
        fi
        
    - name: Archive Bandit Reports
      run: |
        mkdir -p reports/bandit
        mv bandit-*.* reports/bandit/ 2>/dev/null || true
        ls -la reports/bandit/
        
    - name: Upload Bandit Artifacts
      uses: actions/upload-artifact@v4
      if: always()
      with:
        name: bandit-security-reports
        path: reports/bandit/

  # Job 3: Docker Build and Security Scan
  docker-security:
    name: Docker Security Scan
    runs-on: self-hosted
    needs: [setup, sast-scan]
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Build Docker Image Locally
      run: |
        echo "=== BUILDING DOCKER IMAGE ==="
        IMAGE_NAME="local-pygoat"
        IMAGE_TAG="devsecops-$(date +%s)"
        
        # Build the image
        docker build -t ${IMAGE_NAME}:${IMAGE_TAG} .
        docker tag ${IMAGE_NAME}:${IMAGE_TAG} ${IMAGE_NAME}:latest
        
        # Save image info for later steps
        echo "IMAGE_NAME=${IMAGE_NAME}" >> $GITHUB_ENV
        echo "IMAGE_TAG=${IMAGE_TAG}" >> $GITHUB_ENV
        
        echo "Built image: ${IMAGE_NAME}:${IMAGE_TAG}"
        docker images | grep ${IMAGE_NAME}
        
    - name: Docker Scout Quick View
      run: |
        echo "=== DOCKER SCOUT QUICKVIEW ==="
        docker scout quickview ${IMAGE_NAME}:latest || echo "Quickview failed, continuing..."
        
    - name: Docker Scout CVE Analysis (Basic)
      run: |
        echo "=== DOCKER SCOUT CVE ANALYSIS ==="
        docker scout cves ${IMAGE_NAME}:latest || echo "CVE analysis failed, continuing..."
        
    - name: Docker Scout CVE Analysis (Detailed)
      run: |
        echo "=== DOCKER SCOUT DETAILED CVE ANALYSIS ==="
        mkdir -p reports/docker-scout
        
        # Generate different report formats
        docker scout cves ${IMAGE_NAME}:latest --format table --output reports/docker-scout/scout-cves-table.txt || true
        docker scout cves ${IMAGE_NAME}:latest --format json --output reports/docker-scout/scout-cves.json || true
        docker scout cves ${IMAGE_NAME}:latest --format sarif --output reports/docker-scout/scout-cves.sarif || true
        
        # Filter for high/critical only
        docker scout cves ${IMAGE_NAME}:latest --only-severity critical,high --format table --output reports/docker-scout/scout-critical-high.txt || true
        
        echo "=== SCOUT REPORTS GENERATED ==="
        ls -la reports/docker-scout/
        
    - name: Display Docker Scout Results
      run: |
        echo "=== DOCKER SCOUT RESULTS SUMMARY ==="
        if [ -f reports/docker-scout/scout-critical-high.txt ]; then
          echo "--- Critical and High Severity Issues ---"
          cat reports/docker-scout/scout-critical-high.txt
        fi
        
        if [ -f reports/docker-scout/scout-cves-table.txt ]; then
          echo "--- All CVE Issues (First 50 lines) ---"
          head -50 reports/docker-scout/scout-cves-table.txt
        fi
        
    - name: Upload Docker Scout Reports
      uses: actions/upload-artifact@v4
      if: always()
      with:
        name: docker-scout-reports
        path: reports/docker-scout/
        
    - name: Test Application Locally
      run: |
        echo "=== TESTING APPLICATION LOCALLY ==="
        # Start container in background
        CONTAINER_ID=$(docker run -d -p 8000:8000 ${IMAGE_NAME}:latest)
        echo "Started container: $CONTAINER_ID"
        
        # Wait for application to start
        sleep 10
        
        # Test if application is responding
        curl -f http://localhost:8000 || echo "Application health check failed"
        
        # Stop the test container
        docker stop $CONTAINER_ID
        docker rm $CONTAINER_ID
        
        echo "Local testing completed"

  # Job 4: Security Report Analysis
  security-analysis:
    name: Security Analysis & Reporting
    runs-on: self-hosted
    needs: [sast-scan, docker-security]
    if: always()
    
    steps:
    - name: Download All Artifacts
      uses: actions/download-artifact@v4
      
    - name: Generate Security Summary Report
      run: |
        echo "=== GENERATING SECURITY SUMMARY REPORT ==="
        mkdir -p reports/summary
        
        cat > reports/summary/security-summary.md << 'EOF'
        # DevSecOps Security Analysis Report
        
        Generated on: $(date)
        Repository: $(git remote get-url origin)
        Commit: $(git rev-parse HEAD)
        
        ## SAST (Static Application Security Testing) Results
        
        ### Bandit Scan Summary
        - **Tool**: Bandit Python Security Scanner
        - **Scope**: Python source code analysis
        - **Configuration**: Custom severity and confidence filtering
        
        EOF
        
        # Add Bandit results if available
        if [ -f bandit-security-reports/bandit-filtered-report.txt ]; then
          echo "### Filtered Bandit Results" >> reports/summary/security-summary.md
          echo '```' >> reports/summary/security-summary.md
          cat bandit-security-reports/bandit-filtered-report.txt >> reports/summary/security-summary.md
          echo '```' >> reports/summary/security-summary.md
        fi
        
        # Add Docker Scout results if available
        cat >> reports/summary/security-summary.md << 'EOF'
        
        ## Container Security Results
        
        ### Docker Scout Analysis
        - **Tool**: Docker Scout CVE Scanner
        - **Scope**: Container image vulnerabilities
        - **Focus**: Critical and High severity issues
        
        EOF
        
        if [ -f docker-scout-reports/scout-critical-high.txt ]; then
          echo "### Critical and High Severity Issues" >> reports/summary/security-summary.md
          echo '```' >> reports/summary/security-summary.md
          cat docker-scout-reports/scout-critical-high.txt >> reports/summary/security-summary.md
          echo '```' >> reports/summary/security-summary.md
        fi
        
        # Display the summary
        cat reports/summary/security-summary.md
        
    - name: Upload Security Summary
      uses: actions/upload-artifact@v4
      with:
        name: security-summary-report
        path: reports/summary/

  # Job 5: Optional Local Deployment
  local-deploy:
    name: Local Deployment Test
    runs-on: self-hosted
    needs: [docker-security]
    if: github.ref == 'refs/heads/main'
    
    steps:
    - name: Deploy Application Locally
      run: |
        echo "=== DEPLOYING APPLICATION LOCALLY ==="
        
        # Stop any existing PyGoat containers
        docker stop pygoat-local 2>/dev/null || true
        docker rm pygoat-local 2>/dev/null || true
        
        # Start new container
        docker run -d --name pygoat-local -p 8080:8000 local-pygoat:latest
        
        # Wait for startup
        sleep 15
        
        # Verify deployment
        if curl -f http://localhost:8080; then
          echo "Application successfully deployed and accessible at http://localhost:8080"
        else
          echo "Application deployment failed"
          docker logs pygoat-local
          exit 1
        fi
        
    - name: Display Deployment Info
      run: |
        echo "=== DEPLOYMENT INFORMATION ==="
        echo "Application URL: http://localhost:8080"
        echo "Container Status:"
        docker ps | grep pygoat-local
        echo "Container Logs (last 20 lines):"
        docker logs --tail 20 pygoat-local
